In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


In [2]:
%run 02_Daten_laden.ipynb

In [3]:
# Bilde ein Subset mit 1.000 Einträgen
sst2_subset = sst2_combined[:1000]
sst2_subset

index                                           sentence  label
0        0       hide new secretions from the parental units       0
1        1               contains no wit , only labored gags       0
2        2  that loves its characters and communicates som...      1
3        3  remains utterly satisfied to remain the same t...      0
4        4  on the worst revenge-of-the-nerds clichés the ...      0
..     ...                                                ...    ...
995    995  you wish you were at home watching that movie ...      0
996    996  's no point in extracting the bare bones of by...      0
997    997                                    underdeveloped       0
998    998                                the jokes are flat       0
999    999              a heartening tale of small victories       1

[1000 rows x 3 columns]

In [41]:

# sst2 gpt
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_SelfConsistency3_1Exemplar_GPT.csv',sep=',')

## gemini
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_SelfConsistency_GEMINI.csv',sep=',')


df = df[df['generated_label'].isin(['0', '1',0,1])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0              0      0       hide new secretions from the parental units    
1              1      1               contains no wit , only labored gags    
2              2      2  that loves its characters and communicates som...   
3              3      3  remains utterly satisfied to remain the same t...   
4              4      4  on the worst revenge-of-the-nerds clichés the ...   
...          ...    ...                                                ...   
996          996    996  's no point in extracting the bare bones of by...   
997          997    997                                    underdeveloped    
998          998    998                                the jokes are flat    
999          999    999              a heartening tale of small victories    
1000        1000   1000  suspense , intriguing characters and bizarre b...   

                                              all_steps  \
0     [[Step(explanation="The phrase 'hide new secre...   
1     [[Step(explanation='The phrase "contains no wi...   
2     [[Step(explanation="The phrase 'that loves its...   
3     [[Step(explanation="The phrase 'remains utterl...   
4     [[Step(explanation='The phrase "on the worst r...   
...                                                 ...   
996   [[Step(explanation='The phrase "no point in ex...   
997   [[Step(explanation='The term "underdeveloped" ...   
998   [[Step(explanation='The phrase "the jokes are ...   
999   [[Step(explanation='The phrase "a heartening t...   
1000  [[Step(explanation="The text mentions 'suspens...   

                                all_labels  generated_label  
0     ['negative', 'negative', 'negative']                0  
1     ['negative', 'negative', 'negative']                0  
2     ['positive', 'positive', 'positive']                1  
3     ['positive', 'positive', 'negative']                1  
4     ['negative', 'negative', 'negative']                0  
...                                    ...              ...  
996   ['negative', 'negative', 'negative']                0  
997   ['negative', 'negative', 'negative']                0  
998   ['negative', 'negative', 'negative']                0  
999   ['positive', 'positive', 'positive']                1  
1000  ['positive', 'positive', 'positive']                1  

[1001 rows x 6 columns]

In [42]:
# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sst2_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der positiven Klassifikation)
precision = precision_score(true_labels, predicted_labels, pos_label=1)
print(f'Precision: {precision:.2f}')

# 3. Recall (Empfindlichkeit, Trefferquote)
recall = recall_score(true_labels, predicted_labels, pos_label=1)
print(f'Recall: {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall)
f1 = f1_score(true_labels, predicted_labels, pos_label=1)
print(f'F1-Score: {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0,1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.84
Precision: 0.99
Recall: 0.71
F1-Score: 0.83
Confusion Matrix:
[[455   3]
 [157 385]]


In [43]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.99      0.85       458
           1       0.99      0.71      0.83       542

    accuracy                           0.84      1000
   macro avg       0.87      0.85      0.84      1000
weighted avg       0.88      0.84      0.84      1000



# SB10K

In [11]:
sb10k_subset = sb10k_combined[:1000]
sb10k_subset

index                                               Text Sentiment  \
0        0  RT @TheKedosZone : So ein Hearthstone - Key vo...  positive   
1        1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   neutral   
2        2  Aber wenigstens kommt #Supernatural heute mal ...   neutral   
3        3  DARLEHEN - Angebot für Schufa - freie Darlehen...   neutral   
4        4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   neutral   
..     ...                                                ...       ...   
995    995      @sinkingFX Die Liebe unter Verwandten . : ' 3  positive   
996    996                  Cros Kindermusik braucht keiner .  negative   
997    997  RT @ZDFsport : Extrem viele Braunschweiger hie...  positive   
998    998  Moin Moin ... trotz Regen wünsche ich euch ein...  positive   
999    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...  negative   

     sentiment_coded  
0                  1  
1                  2  
2                  2  
3                  2  
4                  2  
..               ...  
995                1  
996                0  
997                1  
998                1  
999                0  

[1000 rows x 4 columns]

In [19]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_SelfConsistency2_GPT.csv',sep=',')
# sst2 gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_SelfConsistency_GEMINI.csv',sep=',')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  RT @TheKedosZone : So ein Hearthstone - Key vo...   
1             1      1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   
2             2      2  Aber wenigstens kommt #Supernatural heute mal ...   
3             3      3  DARLEHEN - Angebot für Schufa - freie Darlehen...   
4             4      4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   
..          ...    ...                                                ...   
950         950    994                 @xilovemichelle_ Kutmichelle =( ..   
951         951    996                  Cros Kindermusik braucht keiner .   
952         952    997  RT @ZDFsport : Extrem viele Braunschweiger hie...   
953         953    998  Moin Moin ... trotz Regen wünsche ich euch ein...   
954         954    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...   

                                             all_steps  \
0    ['Der Satz "RT @TheKedosZone : So ein Hearthst...   
1    ['Der Text „Tainted Talents ( Ateliertagebuch....   
2    ['Der Satz "Aber wenigstens kommt #Supernatura...   
3    ['Der Text „DARLEHEN - Angebot für Schufa - fr...   
4    ['Der Text „ANRUF ERWÜNSCHT : Hardcore Teeny V...   
..                                                 ...   
950  ['Der Text "@xilovemichelle_ Kutmichelle =( .....   
951  ['Der Satz „Cros Kindermusik braucht keiner..“...   
952  ['Der Tweet „RT @ZDFsport : Extrem viele Braun...   
953  ['Der Text „Moin Moin ... trotz Regen wünsche ...   
954  ['Der Tweet „RT @Geisthoernchen : @NewelMedia ...   

                            all_labels  generated_label  
0    ['positiv', 'positiv', 'positiv']                1  
1    ['neutral', 'neutral', 'neutral']                2  
2    ['negativ', 'negativ', 'negativ']                0  
3    ['neutral', 'neutral', 'neutral']                2  
4    ['neutral', 'negativ', 'negativ']                0  
..                                 ...              ...  
950  ['negativ', 'negativ', 'negativ']                0  
951  ['negativ', 'negativ', 'negativ']                0  
952  ['positiv', 'positiv', 'positiv']                1  
953  ['positiv', 'positiv', 'positiv']                1  
954  ['negativ', 'negativ', 'negativ']                0  

[955 rows x 6 columns]

In [20]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sb10k_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.58
Precision (macro): 0.61
Recall (macro): 0.71
F1-Score (macro): 0.58
Confusion Matrix:
[[139   4   7]
 [ 27 176  21]
 [189 153 239]]


In [22]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.39      0.93      0.55       150
           1       0.53      0.79      0.63       224
           2       0.90      0.41      0.56       581

    accuracy                           0.58       955
   macro avg       0.61      0.71      0.58       955
weighted avg       0.73      0.58      0.58       955



# ABSA 

In [23]:
absa_final_subset = absa_final[:1001]
absa_final_subset

index                                           sentence  \
0         0  I charge it at night and skip taking the cord ...   
1         1  I charge it at night and skip taking the cord ...   
2         2  The tech guy then said the service center does...   
3         3  The tech guy then said the service center does...   
4         4  The tech guy then said the service center does...   
...     ...                                                ...   
996     996  iPhotos is an excellent program for storing an...   
997     997  Other than that its a great performing machine...   
998     998  Called tech support and got the usual Acer "We...   
999     999  Called tech support and got the usual Acer "We...   
1000   1000  Called tech support and got the usual Acer "We...   

              aspect  sentiment_coded  polarity  
0               cord                2   neutral  
1       battery life                1  positive  
2     service center                0  negative  
3       "sales" team                0  negative  
4           tech guy                2   neutral  
...              ...              ...       ...  
996          program                1  positive  
997       performing                1  positive  
998         software                0  negative  
999         software                0  negative  
1000         booting                0  negative  

[1001 rows x 5 columns]

In [27]:



# sst2 gpt

#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_SemEval2014_SelfConsistency_GPT.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_SelfConsistency_GEMINI.csv')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  I charge it at night and skip taking the cord ...   
1             1      1  I charge it at night and skip taking the cord ...   
2             2      2  The tech guy then said the service center does...   
3             3      3  The tech guy then said the service center does...   
4             4      4  The tech guy then said the service center does...   
..          ...    ...                                                ...   
968         968    996  iPhotos is an excellent program for storing an...   
969         969    997  Other than that its a great performing machine...   
970         970    998  Called tech support and got the usual Acer "We...   
971         971    999  Called tech support and got the usual Acer "We...   
972         972   1000  Called tech support and got the usual Acer "We...   

             aspect                                          all_steps  \
0              cord  ['The sentence "I charge it at night and skip ...   
1      battery life  ['The statement "I charge it at night and skip...   
2    service center  ["The statement “The tech guy then said the se...   
3      "sales" team  ['The provided text expresses a neutral sentim...   
4          tech guy  ['The provided text expresses a negative senti...   
..              ...                                                ...   
968         program  ["The sentence “iPhotos is an excellent progra...   
969      performing  ['The sentence "Other than that its a great pe...   
970        software  ["The sentence “Called tech support and got th...   
971        software  ['The sentence “Called tech support and got th...   
972         booting  ["The text “Called tech support and got the us...   

                               all_labels  generated_label  
0    ['positive', 'positive', 'positive']                1  
1    ['positive', 'positive', 'positive']                1  
2    ['negative', 'negative', 'negative']                0  
3       ['neutral', 'neutral', 'neutral']                2  
4    ['negative', 'negative', 'negative']                0  
..                                    ...              ...  
968  ['positive', 'positive', 'positive']                1  
969  ['positive', 'positive', 'positive']                1  
970  ['negative', 'negative', 'negative']                0  
971  ['negative', 'negative', 'negative']                0  
972  ['negative', 'negative', 'negative']                0  

[973 rows x 7 columns]

In [28]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(absa_final_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.83
Precision (macro): 0.78
Recall (macro): 0.78
F1-Score (macro): 0.78
Confusion Matrix:
[[326  12  29]
 [ 10 392  35]
 [ 38  38  93]]


In [29]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.89      0.88       367
           1       0.89      0.90      0.89       437
           2       0.59      0.55      0.57       169

    accuracy                           0.83       973
   macro avg       0.78      0.78      0.78       973
weighted avg       0.83      0.83      0.83       973



# Irony 

In [30]:
irony_subset = irony_final[:1001]
irony_subset

index  Label                                               text
0         0      1  Sweet United Nations video. Just in time for C...
1         1      1  @mrdahl87 We are rumored to have talked to Erv...
2         2      1  Hey there! Nice to see you Minnesota/ND Winter...
3         3      0                3 episodes left I'm dying over here
4         4      1  I can't breathe! was chosen as the most notabl...
...     ...    ...                                                ...
996     996      0  It was a greaaaat night! :white_smiling_face:️...
997     997      0  @StephHammy I wonder if they have that in an a...
998     998      0  Queens Of The Stone Age no Rock In Rio http://...
999     999      1  @jordyn_eaton wants me to get hit by a bus so ...
1000   1000      0  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...

[1001 rows x 3 columns]

In [37]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_SelfConsistency_GPT.csv',sep=';')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_SelfConsistency_GEMINI.csv')


df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  Sweet United Nations video. Just in time for C...   
1             1      1  @mrdahl87 We are rumored to have talked to Erv...   
2             2      2  Hey there! Nice to see you Minnesota/ND Winter...   
3             3      3                3 episodes left I'm dying over here   
4             4      4  I can't breathe! was chosen as the most notabl...   
..          ...    ...                                                ...   
992         992    996  It was a greaaaat night! :white_smiling_face:️...   
993         993    997  @StephHammy I wonder if they have that in an a...   
994         994    998  Queens Of The Stone Age no Rock In Rio http://...   
995         995    999  @jordyn_eaton wants me to get hit by a bus so ...   
996         996   1000  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...   

                                             all_steps       all_labels  \
0    ['The text expresses a negative sentiment towa...  ['1', '1', '1']   
1    ["The text uses a wink emoji, which is often u...  ['1', '1', '1']   
2    ["The text expresses a greeting followed by a ...  ['1', '1', '1']   
3    ['The statement "3 episodes left I\'m dying ov...  ['1', '1', '1']   
4    ['The text mentions "I can\'t breathe!" being ...  ['1', '1', '1']   
..                                                 ...              ...   
992  ["The text uses multiple emojis expressing pos...  ['1', '1', '1']   
993  ['The text is a tweet directed at another user...  ['1', '1', '1']   
994  ['The text mentions "Queens Of The Stone Age" ...  ['1', '1', '0']   
995  ['The text expresses a humorous and exaggerate...  ['1', '1', '1']   
996  ['The text uses a colloquial expression "Hold ...  ['1', '1', '1']   

     generated_label  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1  
..               ...  
992                1  
993                1  
994                1  
995                1  
996                1  

[997 rows x 6 columns]

In [38]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(irony_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['Label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels)
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels)
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels)
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.56
Precision (macro): 0.54
Recall (macro): 0.96
F1-Score (macro): 0.69
Confusion Matrix:
[[ 64 423]
 [ 19 491]]


In [40]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.13      0.22       487
           1       0.54      0.96      0.69       510

    accuracy                           0.56       997
   macro avg       0.65      0.55      0.46       997
weighted avg       0.65      0.56      0.46       997

