In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


In [2]:
%run 02_Daten_laden.ipynb

In [3]:
# Bilde ein Subset mit 1.000 Einträgen
sst2_subset = sst2_combined[:1000]
sst2_subset

index                                           sentence  label
0        0       hide new secretions from the parental units       0
1        1               contains no wit , only labored gags       0
2        2  that loves its characters and communicates som...      1
3        3  remains utterly satisfied to remain the same t...      0
4        4  on the worst revenge-of-the-nerds clichés the ...      0
..     ...                                                ...    ...
995    995  you wish you were at home watching that movie ...      0
996    996  's no point in extracting the bare bones of by...      0
997    997                                    underdeveloped       0
998    998                                the jokes are flat       0
999    999              a heartening tale of small victories       1

[1000 rows x 3 columns]

In [7]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_ZeroShot_CoT_GPT.csv',sep=',')

## gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_ZeroShot_CoT_GEMINI.csv',sep=',')


df = df[df['generated_label'].isin(['0', '1',0,1])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0       hide new secretions from the parental units    
1             1      1               contains no wit , only labored gags    
2             2      2  that loves its characters and communicates som...   
3             3      3  remains utterly satisfied to remain the same t...   
4             4      4  on the worst revenge-of-the-nerds clichés the ...   
..          ...    ...                                                ...   
950         995    995  you wish you were at home watching that movie ...   
951         996    996  's no point in extracting the bare bones of by...   
952         997    997                                    underdeveloped    
953         998    998                                the jokes are flat    
954         999    999              a heartening tale of small victories    

                                                 steps  generated_label  
0    The text "hide new secretions from the parenta...                0  
1    The text 'contains no wit , only labored gags ...                0  
2    The text mentions 'loves' and 'beautiful', whi...                1  
3    The phrase "remains utterly satisfied" suggest...                1  
4    The phrase 'worst revenge-of-the-nerds clichés...                0  
..                                                 ...              ...  
950  The text expresses a clear preference for bein...                0  
951  The text expresses a negative sentiment toward...                0  
952  The word "underdeveloped" typically carries a ...                0  
953  The text "the jokes are flat." contains the wo...                0  
954  The text 'a heartening tale of small victories...                1  

[955 rows x 5 columns]

In [8]:
# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sst2_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der positiven Klassifikation)
precision = precision_score(true_labels, predicted_labels, pos_label=1)
print(f'Precision: {precision:.2f}')

# 3. Recall (Empfindlichkeit, Trefferquote)
recall = recall_score(true_labels, predicted_labels, pos_label=1)
print(f'Recall: {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall)
f1 = f1_score(true_labels, predicted_labels, pos_label=1)
print(f'F1-Score: {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0,1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.87
Precision: 0.96
Recall: 0.80
F1-Score: 0.87
Confusion Matrix:
[[430  17]
 [103 405]]


In [9]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.96      0.88       447
           1       0.96      0.80      0.87       508

    accuracy                           0.87       955
   macro avg       0.88      0.88      0.87       955
weighted avg       0.89      0.87      0.87       955



# SB10K

In [10]:
sb10k_subset = sb10k_combined[:1000]
sb10k_subset

index                                               Text Sentiment  \
0        0  RT @TheKedosZone : So ein Hearthstone - Key vo...  positive   
1        1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   neutral   
2        2  Aber wenigstens kommt #Supernatural heute mal ...   neutral   
3        3  DARLEHEN - Angebot für Schufa - freie Darlehen...   neutral   
4        4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   neutral   
..     ...                                                ...       ...   
995    995      @sinkingFX Die Liebe unter Verwandten . : ' 3  positive   
996    996                  Cros Kindermusik braucht keiner .  negative   
997    997  RT @ZDFsport : Extrem viele Braunschweiger hie...  positive   
998    998  Moin Moin ... trotz Regen wünsche ich euch ein...  positive   
999    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...  negative   

     sentiment_coded  
0                  1  
1                  2  
2                  2  
3                  2  
4                  2  
..               ...  
995                1  
996                0  
997                1  
998                1  
999                0  

[1000 rows x 4 columns]

In [16]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_ZeroShot_CoT_GPT.csv',sep=',')
# sst2 gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_ZeroShot_CoT_GEMINI.csv',sep=',')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  RT @TheKedosZone : So ein Hearthstone - Key vo...   
1             1      1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   
2             2      2  Aber wenigstens kommt #Supernatural heute mal ...   
3             3      3  DARLEHEN - Angebot für Schufa - freie Darlehen...   
4             4      4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   
..          ...    ...                                                ...   
994         994    995      @sinkingFX Die Liebe unter Verwandten . : ' 3   
995         995    996                  Cros Kindermusik braucht keiner .   
996         996    997  RT @ZDFsport : Extrem viele Braunschweiger hie...   
997         997    998  Moin Moin ... trotz Regen wünsche ich euch ein...   
998         998    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...   

                                                 steps  generated_label  
0    Der Text drückt eine positive Stimmung aus. De...                1  
1    Der Text "Tainted Talents (Ateliertagebuch.) "...                2  
2    Der Text enthält die Phrase "ein schwacher Tro...                0  
3    Der Text bewirbt Online-Darlehen, die in Deuts...                2  
4    Der Text beginnt mit "ANRUF ERWÜNSCHT", was da...                0  
..                                                 ...              ...  
994  Der Text enthält nur ein Emoticon, welches sch...                2  
995  Der Satz "Cros Kindermusik braucht keiner .." ...                0  
996  Der Text enthält das Emoji :-) , das eine posi...                1  
997  Der Text beginnt mit einem freundlichen Gruß "...                1  
998  Der Text enthält den Satz "der IRAN weiss sehr...                0  

[999 rows x 5 columns]

In [17]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sb10k_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.51
Precision (macro): 0.55
Recall (macro): 0.63
F1-Score (macro): 0.51
Confusion Matrix:
[[148   3   9]
 [ 48 141  45]
 [260 125 220]]


In [18]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.32      0.93      0.48       160
           1       0.52      0.60      0.56       234
           2       0.80      0.36      0.50       605

    accuracy                           0.51       999
   macro avg       0.55      0.63      0.51       999
weighted avg       0.66      0.51      0.51       999



# ABSA 

In [19]:
absa_final_subset = absa_final[:1001]
absa_final_subset

index                                           sentence  \
0         0  I charge it at night and skip taking the cord ...   
1         1  I charge it at night and skip taking the cord ...   
2         2  The tech guy then said the service center does...   
3         3  The tech guy then said the service center does...   
4         4  The tech guy then said the service center does...   
...     ...                                                ...   
996     996  iPhotos is an excellent program for storing an...   
997     997  Other than that its a great performing machine...   
998     998  Called tech support and got the usual Acer "We...   
999     999  Called tech support and got the usual Acer "We...   
1000   1000  Called tech support and got the usual Acer "We...   

              aspect  sentiment_coded  polarity  
0               cord                2   neutral  
1       battery life                1  positive  
2     service center                0  negative  
3       "sales" team                0  negative  
4           tech guy                2   neutral  
...              ...              ...       ...  
996          program                1  positive  
997       performing                1  positive  
998         software                0  negative  
999         software                0  negative  
1000         booting                0  negative  

[1001 rows x 5 columns]

In [26]:



# sst2 gpt

#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_SemEval2014_ZeroCoT_GPT.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_ZeroCoT_GEMINI.csv')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0              0      0  I charge it at night and skip taking the cord ...   
1              1      1  I charge it at night and skip taking the cord ...   
2              2      2  The tech guy then said the service center does...   
3              3      3  The tech guy then said the service center does...   
4              4      4  The tech guy then said the service center does...   
...          ...    ...                                                ...   
996          996    996  iPhotos is an excellent program for storing an...   
997          997    997  Other than that its a great performing machine...   
998          998    998  Called tech support and got the usual Acer "We...   
999          999    999  Called tech support and got the usual Acer "We...   
1000        1000   1000  Called tech support and got the usual Acer "We...   

              aspect                                              steps  \
0               cord  The text mentions 'skip taking the cord' which...   
1       battery life  The text states that the user charges the devi...   
2     service center  The text mentions that the service center "doe...   
3       "sales" team  The text mentions that the customer was direct...   
4           tech guy  The text mentions the tech guy directing the c...   
...              ...                                                ...   
996          program  The text states that iPhotos is an "excellent ...   
997       performing  The text states that the machine is "great per...   
998         software  The text states that Acer tech support said th...   
999         software  The text expresses frustration with Acer's tec...   
1000         booting  The text mentions the user's frustration with ...   

      generated_label  
0                   2  
1                   1  
2                   0  
3                   2  
4                   0  
...               ...  
996                 1  
997                 1  
998                 0  
999                 0  
1000                0  

[1001 rows x 6 columns]

In [27]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(absa_final_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.81
Precision (macro): 0.75
Recall (macro): 0.71
F1-Score (macro): 0.71
Confusion Matrix:
[[347  14  17]
 [ 17 412  19]
 [ 53  71  51]]


In [28]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.92      0.87       378
           1       0.83      0.92      0.87       448
           2       0.59      0.29      0.39       175

    accuracy                           0.81      1001
   macro avg       0.75      0.71      0.71      1001
weighted avg       0.79      0.81      0.79      1001



# Irony 

In [29]:
irony_subset = irony_final[:1001]
irony_subset

index  Label                                               text
0         0      1  Sweet United Nations video. Just in time for C...
1         1      1  @mrdahl87 We are rumored to have talked to Erv...
2         2      1  Hey there! Nice to see you Minnesota/ND Winter...
3         3      0                3 episodes left I'm dying over here
4         4      1  I can't breathe! was chosen as the most notabl...
...     ...    ...                                                ...
996     996      0  It was a greaaaat night! :white_smiling_face:️...
997     997      0  @StephHammy I wonder if they have that in an a...
998     998      0  Queens Of The Stone Age no Rock In Rio http://...
999     999      1  @jordyn_eaton wants me to get hit by a bus so ...
1000   1000      0  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...

[1001 rows x 3 columns]

In [35]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_ZeroShot_CoT_GPT.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_ZeroShot_CoT_GEMINI.csv')


df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  Sweet United Nations video. Just in time for C...   
1             1      1  @mrdahl87 We are rumored to have talked to Erv...   
2             2      2  Hey there! Nice to see you Minnesota/ND Winter...   
3             3      3                3 episodes left I'm dying over here   
4             4      4  I can't breathe! was chosen as the most notabl...   
..          ...    ...                                                ...   
994         994    996  It was a greaaaat night! :white_smiling_face:️...   
995         995    997  @StephHammy I wonder if they have that in an a...   
996         996    998  Queens Of The Stone Age no Rock In Rio http://...   
997         997    999  @jordyn_eaton wants me to get hit by a bus so ...   
998         998   1000  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...   

                                                 steps  generated_label  
0    The text uses the hashtag "#NoReligion" in a t...                1  
1    The text contains a wink emoji ;). The wink em...                1  
2    The text expresses a sense of sarcasm because ...                1  
3    The text "3 episodes left I'm dying over here....                1  
4    The text is ironic because the phrase "I can't...                1  
..                                                 ...              ...  
994  The text uses emojis that are usually associat...                1  
995  The text is a tweet, so the context is importa...                1  
996  The text mentions Queens Of The Stone Age play...                1  
997  The text uses sarcasm because the user is impl...                1  
998  The text uses informal language, like "Hold It...                1  

[999 rows x 5 columns]

In [36]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(irony_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['Label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels)
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels)
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels)
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.55
Precision (macro): 0.53
Recall (macro): 0.97
F1-Score (macro): 0.69
Confusion Matrix:
[[ 52 437]
 [ 14 496]]


In [37]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.11      0.19       489
           1       0.53      0.97      0.69       510

    accuracy                           0.55       999
   macro avg       0.66      0.54      0.44       999
weighted avg       0.66      0.55      0.44       999

