In [9]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


In [2]:
%run 02_Daten_laden.ipynb

In [3]:
# Bilde ein Subset mit 1.000 Einträgen
sst2_subset = sst2_combined[:1000]
sst2_subset

index                                           sentence  label
0        0       hide new secretions from the parental units       0
1        1               contains no wit , only labored gags       0
2        2  that loves its characters and communicates som...      1
3        3  remains utterly satisfied to remain the same t...      0
4        4  on the worst revenge-of-the-nerds clichés the ...      0
..     ...                                                ...    ...
995    995  you wish you were at home watching that movie ...      0
996    996  's no point in extracting the bare bones of by...      0
997    997                                    underdeveloped       0
998    998                                the jokes are flat       0
999    999              a heartening tale of small victories       1

[1000 rows x 3 columns]

In [41]:

# sst2 gpt
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_BASELINE_GPT.csv',sep=';')
# sst2 gemini
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_BASELINE_GEMINI.csv',sep=';')

df = df[df['generated_label'].isin(['0', '1',0,1])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0       hide new secretions from the parental units    
1             1      1               contains no wit , only labored gags    
2             2      2  that loves its characters and communicates som...   
3             3      3  remains utterly satisfied to remain the same t...   
4             4      4  on the worst revenge-of-the-nerds clichés the ...   
..          ...    ...                                                ...   
992         995    995  you wish you were at home watching that movie ...   
993         996    996  's no point in extracting the bare bones of by...   
994         997    997                                    underdeveloped    
995         998    998                                the jokes are flat    
996         999    999              a heartening tale of small victories    

     generated_label  
0                  0  
1                  0  
2                  1  
3                  1  
4                  0  
..               ...  
992                0  
993                0  
994                0  
995                0  
996                1  

[993 rows x 4 columns]

In [42]:
# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sst2_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der positiven Klassifikation)
precision = precision_score(true_labels, predicted_labels, pos_label=1)
print(f'Precision: {precision:.2f}')

# 3. Recall (Empfindlichkeit, Trefferquote)
recall = recall_score(true_labels, predicted_labels, pos_label=1)
print(f'Recall: {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall)
f1 = f1_score(true_labels, predicted_labels, pos_label=1)
print(f'F1-Score: {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0,1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.91
Precision: 0.97
Recall: 0.86
F1-Score: 0.91
Confusion Matrix:
[[439  15]
 [ 76 463]]


In [43]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.97      0.91       454
           1       0.97      0.86      0.91       539

    accuracy                           0.91       993
   macro avg       0.91      0.91      0.91       993
weighted avg       0.92      0.91      0.91       993



# SB10K

In [32]:
sb10k_subset = sb10k_combined[:1000]
sb10k_subset

index                                               Text Sentiment  \
0        0  RT @TheKedosZone : So ein Hearthstone - Key vo...  positive   
1        1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   neutral   
2        2  Aber wenigstens kommt #Supernatural heute mal ...   neutral   
3        3  DARLEHEN - Angebot für Schufa - freie Darlehen...   neutral   
4        4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   neutral   
..     ...                                                ...       ...   
995    995      @sinkingFX Die Liebe unter Verwandten . : ' 3  positive   
996    996                  Cros Kindermusik braucht keiner .  negative   
997    997  RT @ZDFsport : Extrem viele Braunschweiger hie...  positive   
998    998  Moin Moin ... trotz Regen wünsche ich euch ein...  positive   
999    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...  negative   

     sentiment_coded  
0                  1  
1                  2  
2                  2  
3                  2  
4                  2  
..               ...  
995                1  
996                0  
997                1  
998                1  
999                0  

[1000 rows x 4 columns]

In [47]:

# sst2 gpt
# df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_BASELINE_GPT.csv',sep=';')
# sst2 gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_BASELINE_GEMINI.csv',sep=',')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  RT @TheKedosZone : So ein Hearthstone - Key vo...   
1             1      1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   
2             2      2  Aber wenigstens kommt #Supernatural heute mal ...   
3             3      3  DARLEHEN - Angebot für Schufa - freie Darlehen...   
4             4      4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   
..          ...    ...                                                ...   
994         994    995      @sinkingFX Die Liebe unter Verwandten . : ' 3   
995         995    996                  Cros Kindermusik braucht keiner .   
996         996    997  RT @ZDFsport : Extrem viele Braunschweiger hie...   
997         997    998  Moin Moin ... trotz Regen wünsche ich euch ein...   
998         998    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...   

     generated_label  
0                  1  
1                  2  
2                  0  
3                  2  
4                  0  
..               ...  
994                2  
995                0  
996                1  
997                1  
998                0  

[999 rows x 4 columns]

In [48]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sb10k_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.52
Precision (macro): 0.57
Recall (macro): 0.65
F1-Score (macro): 0.53
Confusion Matrix:
[[151   2   8]
 [ 45 152  37]
 [260 123 221]]


In [49]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.33      0.94      0.49       161
           1       0.55      0.65      0.59       234
           2       0.83      0.37      0.51       604

    accuracy                           0.52       999
   macro avg       0.57      0.65      0.53       999
weighted avg       0.68      0.52      0.53       999



# ABSA 

In [5]:
absa_final_subset = absa_final[:1001]
absa_final_subset

index                                           sentence  \
0         0  I charge it at night and skip taking the cord ...   
1         1  I charge it at night and skip taking the cord ...   
2         2  The tech guy then said the service center does...   
3         3  The tech guy then said the service center does...   
4         4  The tech guy then said the service center does...   
...     ...                                                ...   
996     996  iPhotos is an excellent program for storing an...   
997     997  Other than that its a great performing machine...   
998     998  Called tech support and got the usual Acer "We...   
999     999  Called tech support and got the usual Acer "We...   
1000   1000  Called tech support and got the usual Acer "We...   

              aspect  sentiment_coded  polarity  
0               cord                2   neutral  
1       battery life                1  positive  
2     service center                0  negative  
3       "sales" team                0  negative  
4           tech guy                2   neutral  
...              ...              ...       ...  
996          program                1  positive  
997       performing                1  positive  
998         software                0  negative  
999         software                0  negative  
1000         booting                0  negative  

[1001 rows x 5 columns]

In [13]:

# sst2 gpt
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_BASELINE_GEMINI.csv')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0              0      0  I charge it at night and skip taking the cord ...   
1              1      1  I charge it at night and skip taking the cord ...   
2              2      2  The tech guy then said the service center does...   
3              3      3  The tech guy then said the service center does...   
4              4      4  The tech guy then said the service center does...   
...          ...    ...                                                ...   
996          996    996  iPhotos is an excellent program for storing an...   
997          997    997  Other than that its a great performing machine...   
998          998    998  Called tech support and got the usual Acer "We...   
999          999    999  Called tech support and got the usual Acer "We...   
1000        1000   1000  Called tech support and got the usual Acer "We...   

              aspect  generated_label  
0               cord                2  
1       battery life                1  
2     service center                0  
3       "sales" team                0  
4           tech guy                0  
...              ...              ...  
996          program                1  
997       performing                1  
998         software                0  
999         software                0  
1000         booting                0  

[1001 rows x 5 columns]

In [14]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(absa_final_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.83
Precision (macro): 0.81
Recall (macro): 0.74
F1-Score (macro): 0.74
Confusion Matrix:
[[359  10   9]
 [ 25 412  11]
 [ 70  46  59]]


In [15]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.95      0.86       378
           1       0.88      0.92      0.90       448
           2       0.75      0.34      0.46       175

    accuracy                           0.83      1001
   macro avg       0.81      0.74      0.74      1001
weighted avg       0.82      0.83      0.81      1001



# Irony 

In [16]:
irony_subset = irony_final[:1001]
irony_subset

index  Label                                               text
0         0      1  Sweet United Nations video. Just in time for C...
1         1      1  @mrdahl87 We are rumored to have talked to Erv...
2         2      1  Hey there! Nice to see you Minnesota/ND Winter...
3         3      0                3 episodes left I'm dying over here
4         4      1  I can't breathe! was chosen as the most notabl...
...     ...    ...                                                ...
996     996      0  It was a greaaaat night! :white_smiling_face:️...
997     997      0  @StephHammy I wonder if they have that in an a...
998     998      0  Queens Of The Stone Age no Rock In Rio http://...
999     999      1  @jordyn_eaton wants me to get hit by a bus so ...
1000   1000      0  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...

[1001 rows x 3 columns]

In [21]:

# sst2 gpt
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_BASELINE_GEMINI.csv')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  Sweet United Nations video. Just in time for C...   
1             1      1  @mrdahl87 We are rumored to have talked to Erv...   
2             2      2  Hey there! Nice to see you Minnesota/ND Winter...   
3             3      3                3 episodes left I'm dying over here   
4             4      4  I can't breathe! was chosen as the most notabl...   
..          ...    ...                                                ...   
995         995    996  It was a greaaaat night! :white_smiling_face:️...   
996         996    997  @StephHammy I wonder if they have that in an a...   
997         997    998  Queens Of The Stone Age no Rock In Rio http://...   
998         998    999  @jordyn_eaton wants me to get hit by a bus so ...   
999         999   1000  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...   

     generated_label  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1  
..               ...  
995                1  
996                1  
997                1  
998                1  
999                1  

[1000 rows x 4 columns]

In [22]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(irony_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['Label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels)
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels)
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels)
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.54
Precision (macro): 0.52
Recall (macro): 0.99
F1-Score (macro): 0.69
Confusion Matrix:
[[ 31 458]
 [  6 505]]


In [23]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.06      0.12       489
           1       0.52      0.99      0.69       511

    accuracy                           0.54      1000
   macro avg       0.68      0.53      0.40      1000
weighted avg       0.68      0.54      0.41      1000

