In [2]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


In [5]:
%run 02_Daten_laden.ipynb

In [6]:
# Bilde ein Subset mit 1.000 Einträgen
sst2_subset = sst2_combined[:1000]
sst2_subset

index                                           sentence  label
0        0       hide new secretions from the parental units       0
1        1               contains no wit , only labored gags       0
2        2  that loves its characters and communicates som...      1
3        3  remains utterly satisfied to remain the same t...      0
4        4  on the worst revenge-of-the-nerds clichés the ...      0
..     ...                                                ...    ...
995    995  you wish you were at home watching that movie ...      0
996    996  's no point in extracting the bare bones of by...      0
997    997                                    underdeveloped       0
998    998                                the jokes are flat       0
999    999              a heartening tale of small victories       1

[1000 rows x 3 columns]

In [9]:

# sst2 gpt
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_ONE_SHOT_GEMINI.csv',sep=',')


df = df[df['generated_label'].isin(['0', '1',0,1])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0       hide new secretions from the parental units    
1             1      1               contains no wit , only labored gags    
2             2      2  that loves its characters and communicates som...   
3             3      3  remains utterly satisfied to remain the same t...   
4             4      4  on the worst revenge-of-the-nerds clichés the ...   
..          ...    ...                                                ...   
977         977    995  you wish you were at home watching that movie ...   
978         978    996  's no point in extracting the bare bones of by...   
979         979    997                                    underdeveloped    
980         980    998                                the jokes are flat    
981         981    999              a heartening tale of small victories    

     generated_label  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  
..               ...  
977                0  
978                0  
979                0  
980                0  
981                1  

[982 rows x 4 columns]

In [11]:
# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sst2_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der positiven Klassifikation)
precision = precision_score(true_labels, predicted_labels, pos_label=1)
print(f'Precision: {precision:.2f}')

# 3. Recall (Empfindlichkeit, Trefferquote)
recall = recall_score(true_labels, predicted_labels, pos_label=1)
print(f'Recall: {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall)
f1 = f1_score(true_labels, predicted_labels, pos_label=1)
print(f'F1-Score: {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0,1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.89
Precision: 0.99
Recall: 0.81
F1-Score: 0.89
Confusion Matrix:
[[436   5]
 [101 440]]


In [11]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.99      0.89       441
           1       0.99      0.81      0.89       541

    accuracy                           0.89       982
   macro avg       0.90      0.90      0.89       982
weighted avg       0.91      0.89      0.89       982



# McNemar-Test

# SB10K

In [12]:
sb10k_subset = sb10k_combined[:1000]
sb10k_subset

index                                               Text Sentiment  \
0        0  RT @TheKedosZone : So ein Hearthstone - Key vo...  positive   
1        1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   neutral   
2        2  Aber wenigstens kommt #Supernatural heute mal ...   neutral   
3        3  DARLEHEN - Angebot für Schufa - freie Darlehen...   neutral   
4        4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   neutral   
..     ...                                                ...       ...   
995    995      @sinkingFX Die Liebe unter Verwandten . : ' 3  positive   
996    996                  Cros Kindermusik braucht keiner .  negative   
997    997  RT @ZDFsport : Extrem viele Braunschweiger hie...  positive   
998    998  Moin Moin ... trotz Regen wünsche ich euch ein...  positive   
999    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...  negative   

     sentiment_coded  
0                  1  
1                  2  
2                  2  
3                  2  
4                  2  
..               ...  
995                1  
996                0  
997                1  
998                1  
999                0  

[1000 rows x 4 columns]

In [16]:

# sst2 gpt
# df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_BASELINE_GPT.csv',sep=';')
# sst2 gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_ONE_SHOT_GEMINI.csv',sep=',')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  RT @TheKedosZone : So ein Hearthstone - Key vo...   
1             1      1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   
2             2      2  Aber wenigstens kommt #Supernatural heute mal ...   
3             3      3  DARLEHEN - Angebot für Schufa - freie Darlehen...   
4             4      4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   
..          ...    ...                                                ...   
980         980    995      @sinkingFX Die Liebe unter Verwandten . : ' 3   
981         981    996                  Cros Kindermusik braucht keiner .   
982         982    997  RT @ZDFsport : Extrem viele Braunschweiger hie...   
983         983    998  Moin Moin ... trotz Regen wünsche ich euch ein...   
984         984    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...   

     generated_label  
0                  1  
1                  2  
2                  0  
3                  2  
4                  0  
..               ...  
980                2  
981                0  
982                1  
983                2  
984                2  

[985 rows x 4 columns]

In [17]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sb10k_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.59
Precision (macro): 0.59
Recall (macro): 0.67
F1-Score (macro): 0.58
Confusion Matrix:
[[136   3  15]
 [ 31 144  57]
 [207  89 303]]


In [18]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.36      0.88      0.52       154
           1       0.61      0.62      0.62       232
           2       0.81      0.51      0.62       599

    accuracy                           0.59       985
   macro avg       0.59      0.67      0.58       985
weighted avg       0.69      0.59      0.60       985



# ABSA 

In [19]:
absa_final_subset = absa_final[:1001]
absa_final_subset

index                                           sentence  \
0         0  I charge it at night and skip taking the cord ...   
1         1  I charge it at night and skip taking the cord ...   
2         2  The tech guy then said the service center does...   
3         3  The tech guy then said the service center does...   
4         4  The tech guy then said the service center does...   
...     ...                                                ...   
996     996  iPhotos is an excellent program for storing an...   
997     997  Other than that its a great performing machine...   
998     998  Called tech support and got the usual Acer "We...   
999     999  Called tech support and got the usual Acer "We...   
1000   1000  Called tech support and got the usual Acer "We...   

              aspect  sentiment_coded  polarity  
0               cord                2   neutral  
1       battery life                1  positive  
2     service center                0  negative  
3       "sales" team                0  negative  
4           tech guy                2   neutral  
...              ...              ...       ...  
996          program                1  positive  
997       performing                1  positive  
998         software                0  negative  
999         software                0  negative  
1000         booting                0  negative  

[1001 rows x 5 columns]

In [24]:



# sst2 gpt

#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_SemEval2014_OneShot_GPT.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_OneShot_GEMINI.csv')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0              0      0  I charge it at night and skip taking the cord ...   
1              1      1  I charge it at night and skip taking the cord ...   
2              2      2  The tech guy then said the service center does...   
3              3      3  The tech guy then said the service center does...   
4              4      4  The tech guy then said the service center does...   
...          ...    ...                                                ...   
996          996    996  iPhotos is an excellent program for storing an...   
997          997    997  Other than that its a great performing machine...   
998          998    998  Called tech support and got the usual Acer "We...   
999          999    999  Called tech support and got the usual Acer "We...   
1000        1000   1000  Called tech support and got the usual Acer "We...   

              aspect  generated_label  
0               cord                2  
1       battery life                1  
2     service center                0  
3       "sales" team                0  
4           tech guy                0  
...              ...              ...  
996          program                1  
997       performing                1  
998         software                0  
999         software                0  
1000         booting                0  

[1001 rows x 5 columns]

In [25]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(absa_final_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.83
Precision (macro): 0.80
Recall (macro): 0.74
F1-Score (macro): 0.75
Confusion Matrix:
[[356  14   8]
 [ 25 408  15]
 [ 67  43  65]]


In [27]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.94      0.86       378
           1       0.88      0.91      0.89       448
           2       0.74      0.37      0.49       175

    accuracy                           0.83      1001
   macro avg       0.80      0.74      0.75      1001
weighted avg       0.82      0.83      0.81      1001



# Irony 

In [28]:
irony_subset = irony_final[:1001]
irony_subset

index  Label                                               text
0         0      1  Sweet United Nations video. Just in time for C...
1         1      1  @mrdahl87 We are rumored to have talked to Erv...
2         2      1  Hey there! Nice to see you Minnesota/ND Winter...
3         3      0                3 episodes left I'm dying over here
4         4      1  I can't breathe! was chosen as the most notabl...
...     ...    ...                                                ...
996     996      0  It was a greaaaat night! :white_smiling_face:️...
997     997      0  @StephHammy I wonder if they have that in an a...
998     998      0  Queens Of The Stone Age no Rock In Rio http://...
999     999      1  @jordyn_eaton wants me to get hit by a bus so ...
1000   1000      0  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...

[1001 rows x 3 columns]

In [33]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_SemEval2018_OneShot_GPT4o.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_OneShot_GEMINI.csv')


df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0              0      0  Sweet United Nations video. Just in time for C...   
1              1      1  @mrdahl87 We are rumored to have talked to Erv...   
2              2      2  Hey there! Nice to see you Minnesota/ND Winter...   
3              3      3                3 episodes left I'm dying over here   
4              4      4  I can't breathe! was chosen as the most notabl...   
...          ...    ...                                                ...   
996          996    996  It was a greaaaat night! :white_smiling_face:️...   
997          997    997  @StephHammy I wonder if they have that in an a...   
998          998    998  Queens Of The Stone Age no Rock In Rio http://...   
999          999    999  @jordyn_eaton wants me to get hit by a bus so ...   
1000        1000   1000  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...   

      generated_label  
0                   1  
1                   1  
2                   1  
3                   1  
4                   1  
...               ...  
996                 1  
997                 0  
998                 0  
999                 1  
1000                1  

[1001 rows x 4 columns]

In [34]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(irony_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['Label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels)
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels)
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels)
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.62
Precision (macro): 0.58
Recall (macro): 0.94
F1-Score (macro): 0.71
Confusion Matrix:
[[139 351]
 [ 33 478]]


In [36]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.28      0.42       490
           1       0.58      0.94      0.71       511

    accuracy                           0.62      1001
   macro avg       0.69      0.61      0.57      1001
weighted avg       0.69      0.62      0.57      1001

