In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix


In [2]:
%run 02_Daten_laden.ipynb

In [3]:
# Bilde ein Subset mit 1.000 Einträgen
sst2_subset = sst2_combined[:1000]
sst2_subset

index                                           sentence  label
0        0       hide new secretions from the parental units       0
1        1               contains no wit , only labored gags       0
2        2  that loves its characters and communicates som...      1
3        3  remains utterly satisfied to remain the same t...      0
4        4  on the worst revenge-of-the-nerds clichés the ...      0
..     ...                                                ...    ...
995    995  you wish you were at home watching that movie ...      0
996    996  's no point in extracting the bare bones of by...      0
997    997                                    underdeveloped       0
998    998                                the jokes are flat       0
999    999              a heartening tale of small victories       1

[1000 rows x 3 columns]

In [14]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_CoT_GPT.csv',sep=',')

# gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SST2_CoT_GEMINI.csv',sep=',')


df = df[df['generated_label'].isin(['0', '1',0,1])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0       hide new secretions from the parental units    
1             1      1               contains no wit , only labored gags    
2             2      2  that loves its characters and communicates som...   
3             3      3  remains utterly satisfied to remain the same t...   
4             4      4  on the worst revenge-of-the-nerds clichés the ...   
..          ...    ...                                                ...   
990         990    995  you wish you were at home watching that movie ...   
991         991    996  's no point in extracting the bare bones of by...   
992         992    997                                    underdeveloped    
993         993    998                                the jokes are flat    
994         994    999              a heartening tale of small victories    

                                                 steps  generated_label  
0    The text "hide new secretions from the parenta...                0  
1    The text “contains no wit, only labored gags” ...                0  
2    The sentence "that loves its characters and co...                1  
3    The provided text “remains utterly satisfied t...                0  
4    The phrase "on the worst revenge-of-the-nerds ...                0  
..                                                 ...              ...  
990  The sentence expresses a clear preference for ...                0  
991  The text “s no point in extracting the bare bo...                0  
992  The word “underdeveloped” is inherently negati...                0  
993  The sentence “the jokes are flat” suggests a l...                0  
994  The phrase "a heartening tale of small victori...                1  

[839 rows x 5 columns]

In [15]:
# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sst2_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der positiven Klassifikation)
precision = precision_score(true_labels, predicted_labels, pos_label=1)
print(f'Precision: {precision:.2f}')

# 3. Recall (Empfindlichkeit, Trefferquote)
recall = recall_score(true_labels, predicted_labels, pos_label=1)
print(f'Recall: {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall)
f1 = f1_score(true_labels, predicted_labels, pos_label=1)
print(f'F1-Score: {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0,1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.95
Precision: 0.97
Recall: 0.94
F1-Score: 0.96
Confusion Matrix:
[[390  12]
 [ 26 411]]


In [17]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.97      0.95       402
           1       0.97      0.94      0.96       437

    accuracy                           0.95       839
   macro avg       0.95      0.96      0.95       839
weighted avg       0.96      0.95      0.95       839



# SB10K

In [18]:
sb10k_subset = sb10k_combined[:1000]
sb10k_subset

index                                               Text Sentiment  \
0        0  RT @TheKedosZone : So ein Hearthstone - Key vo...  positive   
1        1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   neutral   
2        2  Aber wenigstens kommt #Supernatural heute mal ...   neutral   
3        3  DARLEHEN - Angebot für Schufa - freie Darlehen...   neutral   
4        4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   neutral   
..     ...                                                ...       ...   
995    995      @sinkingFX Die Liebe unter Verwandten . : ' 3  positive   
996    996                  Cros Kindermusik braucht keiner .  negative   
997    997  RT @ZDFsport : Extrem viele Braunschweiger hie...  positive   
998    998  Moin Moin ... trotz Regen wünsche ich euch ein...  positive   
999    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...  negative   

     sentiment_coded  
0                  1  
1                  2  
2                  2  
3                  2  
4                  2  
..               ...  
995                1  
996                0  
997                1  
998                1  
999                0  

[1000 rows x 4 columns]

In [23]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_CoT_GPT.csv',sep=',')
# sst2 gemini
df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/SC_SB10k_CoT_GEMINI.csv',sep=',')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  RT @TheKedosZone : So ein Hearthstone - Key vo...   
1             1      1  Tainted Talents ( Ateliertagebuch. ) " Wir sin...   
2             2      2  Aber wenigstens kommt #Supernatural heute mal ...   
3             3      3  DARLEHEN - Angebot für Schufa - freie Darlehen...   
4             4      4  ANRUF ERWÜNSCHT : Hardcore Teeny Vicky Carrera...   
..          ...    ...                                                ...   
960         967    995      @sinkingFX Die Liebe unter Verwandten . : ' 3   
961         968    996                  Cros Kindermusik braucht keiner .   
962         969    997  RT @ZDFsport : Extrem viele Braunschweiger hie...   
963         970    998  Moin Moin ... trotz Regen wünsche ich euch ein...   
964         971    999  RT @Geisthoernchen : @NewelMedia Tja , der IRA...   

                                                 steps  generated_label  
0    Der Text „RT @TheKedosZone: So ein Hearthstone...                1  
1    Der Text „Tainted Talents ( Ateliertagebuch. )...                2  
2    Der Text „Aber wenigstens kommt #Supernatural ...                0  
3    Der Text „DARLEHEN - Angebot für Schufa - frei...                2  
4    Der Text „ANRUF ERWÜNSCHT : Hardcore Teeny Vic...                0  
..                                                 ...              ...  
960  Der Satz „@sinkingFX Die Liebe unter Verwandte...                2  
961  Der Satz „Cros Kindermusik braucht keiner.“ is...                0  
962  Der Text „RT @ZDFsport: Extrem viele Braunschw...                1  
963  Der Text „Moin Moin ... trotz Regen wünsche ic...                1  
964  Der Text „RT @Geisthoernchen : @NewelMedia Tja...                0  

[965 rows x 5 columns]

In [24]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(sb10k_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.55
Precision (macro): 0.59
Recall (macro): 0.69
F1-Score (macro): 0.56
Confusion Matrix:
[[143   6   8]
 [ 31 177  16]
 [207 165 212]]


In [25]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.38      0.91      0.53       157
           1       0.51      0.79      0.62       224
           2       0.90      0.36      0.52       584

    accuracy                           0.55       965
   macro avg       0.59      0.69      0.56       965
weighted avg       0.72      0.55      0.54       965



# ABSA 

In [26]:
absa_final_subset = absa_final[:1001]
absa_final_subset

index                                           sentence  \
0         0  I charge it at night and skip taking the cord ...   
1         1  I charge it at night and skip taking the cord ...   
2         2  The tech guy then said the service center does...   
3         3  The tech guy then said the service center does...   
4         4  The tech guy then said the service center does...   
...     ...                                                ...   
996     996  iPhotos is an excellent program for storing an...   
997     997  Other than that its a great performing machine...   
998     998  Called tech support and got the usual Acer "We...   
999     999  Called tech support and got the usual Acer "We...   
1000   1000  Called tech support and got the usual Acer "We...   

              aspect  sentiment_coded  polarity  
0               cord                2   neutral  
1       battery life                1  positive  
2     service center                0  negative  
3       "sales" team                0  negative  
4           tech guy                2   neutral  
...              ...              ...       ...  
996          program                1  positive  
997       performing                1  positive  
998         software                0  negative  
999         software                0  negative  
1000         booting                0  negative  

[1001 rows x 5 columns]

In [30]:



# sst2 gpt

#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_SemEval2014_CoT_GPT.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/ABSA_CoT_GEMINI.csv')

df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  I charge it at night and skip taking the cord ...   
1             1      1  I charge it at night and skip taking the cord ...   
2             2      2  The tech guy then said the service center does...   
3             3      3  The tech guy then said the service center does...   
4             4      4  The tech guy then said the service center does...   
..          ...    ...                                                ...   
993         993    996  iPhotos is an excellent program for storing an...   
994         994    997  Other than that its a great performing machine...   
995         995    998  Called tech support and got the usual Acer "We...   
996         996    999  Called tech support and got the usual Acer "We...   
997         997   1000  Called tech support and got the usual Acer "We...   

             aspect                                              steps  \
0              cord  The sentence “I charge it at night and skip ta...   
1      battery life  The statement “I charge it at night and skip t...   
2    service center  The provided text expresses a negative sentime...   
3      "sales" team  The provided text expresses a neutral sentimen...   
4          tech guy  The sentence “The tech guy then said the servi...   
..              ...                                                ...   
993         program  The sentence “iPhotos is an excellent program ...   
994      performing  The sentence “Other than that its a great perf...   
995        software  The sentence “Called tech support and got the ...   
996        software  The provided text expresses a negative sentime...   
997         booting  The provided text expresses a negative sentime...   

     generated_label  
0                  1  
1                  1  
2                  0  
3                  2  
4                  0  
..               ...  
993                1  
994                1  
995                0  
996                0  
997                0  

[998 rows x 6 columns]

In [31]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(absa_final_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['sentiment_coded']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels, average='macro')
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels, average='macro')
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels, average='macro')
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1, 2])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.83
Precision (macro): 0.78
Recall (macro): 0.78
F1-Score (macro): 0.78
Confusion Matrix:
[[333  11  34]
 [  9 402  35]
 [ 39  38  97]]


In [33]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.88      0.88       378
           1       0.89      0.90      0.90       446
           2       0.58      0.56      0.57       174

    accuracy                           0.83       998
   macro avg       0.78      0.78      0.78       998
weighted avg       0.83      0.83      0.83       998



# Irony 

In [34]:
irony_subset = irony_final[:1001]
irony_subset

index  Label                                               text
0         0      1  Sweet United Nations video. Just in time for C...
1         1      1  @mrdahl87 We are rumored to have talked to Erv...
2         2      1  Hey there! Nice to see you Minnesota/ND Winter...
3         3      0                3 episodes left I'm dying over here
4         4      1  I can't breathe! was chosen as the most notabl...
...     ...    ...                                                ...
996     996      0  It was a greaaaat night! :white_smiling_face:️...
997     997      0  @StephHammy I wonder if they have that in an a...
998     998      0  Queens Of The Stone Age no Rock In Rio http://...
999     999      1  @jordyn_eaton wants me to get hit by a bus so ...
1000   1000      0  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...

[1001 rows x 3 columns]

In [39]:

# sst2 gpt
#df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_COT_GPT.csv')

df = pd.read_csv('/Users/marvinschmitt/Library/CloudStorage/OneDrive-Persönlich/M.Sc. Data Science/17 Masterarbeit/Repo/Prod/CSVs/MAST_CoT_GEMINI.csv')


df = df[df['generated_label'].isin(['0', '1',0,1,'2',2])]

df['generated_label'] = df['generated_label'].astype(int)

df

Unnamed: 0  index                                           sentence  \
0             0      0  Sweet United Nations video. Just in time for C...   
1             1      1  @mrdahl87 We are rumored to have talked to Erv...   
2             2      2  Hey there! Nice to see you Minnesota/ND Winter...   
3             3      3                3 episodes left I'm dying over here   
4             4      4  I can't breathe! was chosen as the most notabl...   
..          ...    ...                                                ...   
991         991    996  It was a greaaaat night! :white_smiling_face:️...   
992         992    997  @StephHammy I wonder if they have that in an a...   
993         993    998  Queens Of The Stone Age no Rock In Rio http://...   
994         994    999  @jordyn_eaton wants me to get hit by a bus so ...   
995         995   1000  Hold It Bub! >> http://t.co/M4UO2D7UuF >> #car...   

                                                 steps  generated_label  
0    The text mentions a "Sweet United Nations vide...                1  
1    The text "@mrdahl87 We are rumored to have tal...                1  
2    The sentence "Hey there! Nice to see you Minne...                1  
3    The phrase "3 episodes left I'm dying over her...                1  
4    The text 'I can't breathe! was chosen as the m...                1  
..                                                 ...              ...  
991  The text uses excessive emojis and exclamation...                1  
992  The text "@StephHammy I wonder if they have th...                0  
993  The text "Queens Of The Stone Age no Rock In R...                0  
994  The sentence "@jordyn_eaton wants me to get hi...                1  
995  The text "Hold It Bub! >> http://t.co/M4UO2D7U...                1  

[996 rows x 5 columns]

In [40]:

# Beide DataFrames anhand der 'index'-Spalte mergen
df_combined = pd.merge(irony_subset, df, on='index')

# Die Spalten 'label' und 'generated_label' sollten die tatsächlichen und vorhergesagten Labels enthalten
true_labels = df_combined['Label']  # Tatsächliche Labels (z.B. aus SST2)
predicted_labels = df_combined['generated_label']  # Vorhergesagte Labels (z.B. aus GPT)

# 1. Accuracy (Genauigkeit)
accuracy = accuracy_score(true_labels, predicted_labels)
print(f'Accuracy: {accuracy:.2f}')

# 2. Precision (Genauigkeit der Klassifikation für alle Klassen)
precision = precision_score(true_labels, predicted_labels)
print(f'Precision (macro): {precision:.2f}')

# 3. Recall (Empfindlichkeit für alle Klassen)
recall = recall_score(true_labels, predicted_labels)
print(f'Recall (macro): {recall:.2f}')

# 4. F1-Score (harmonisches Mittel von Precision und Recall für alle Klassen)
f1 = f1_score(true_labels, predicted_labels)
print(f'F1-Score (macro): {f1:.2f}')

# 5. Confusion Matrix (Verwirrungsmatrix)
conf_matrix = confusion_matrix(true_labels, predicted_labels, labels=[0, 1])
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.63
Precision (macro): 0.59
Recall (macro): 0.88
F1-Score (macro): 0.71
Confusion Matrix:
[[180 308]
 [ 60 448]]


In [41]:
print("\nClassification Report:")
print(classification_report(true_labels, predicted_labels))


Classification Report:
              precision    recall  f1-score   support

           0       0.75      0.37      0.49       488
           1       0.59      0.88      0.71       508

    accuracy                           0.63       996
   macro avg       0.67      0.63      0.60       996
weighted avg       0.67      0.63      0.60       996

